/**
 * Realtime DB schema types.
 *
 * Source-of-truth for every record we store in RTDB. Every Firebase Admin
 * or Web SDK call should type-check against these so that field renames
 * surface at compile time instead of at runtime.
 *
 * Notes on the RTDB shape:
 *   - Collection paths mirror the old Postgres table names so the migration
 *     script and the app talk about the same domain language.
 *   - IDs at every collection level are preserved as the original Supabase
 *     UUIDs — keeps the data migration idempotent.
 *   - Denormalized index collections (byEmail, byApplicant) live alongside
 *     the canonical record so we can satisfy equality lookups without
 *     shipping all records to the client.
 */

export type ApplicantId = string; // UUID v4 from Supabase
export type VideoSubmissionId = string;
export type VerificationId = string;
export type TemplateKey = string;
export type EmailLookupKey = string;

export type EmailResponseStatus = "pending" | "queued" | "sent";
export type VideoInviteWindow = "tue" | "fri";
export type VideoReviewStatus = "pending" | "approved" | "rejected" | "action_required";
export type VerificationReviewStatus = "Pending" | "Approved" | "Rejected";
export type ApplicantStatus = "Active" | "Rejected" | "Inactive";

export type Applicant = {
  id: ApplicantId;

  // Personal & Contact (step 1)
  firstName: string;
  lastName: string;
  phone: string;
  email: string;
  ageRange: string;
  gender: string;
  stateCountry: string;
  linkedin: string | null;
  businessSocial: string | null;

  // Business & Idea (step 2)
  businessName: string;
  businessStage: string;
  industry: string;
  otherIndustry: string | null;
  businessDescription: string;
  problemSolved: string;
  targetCustomers: string;
  businessRegistered: string;
  generatesRevenue: string;
  revenueProgress: string | null;
  growthPotential: string;
  longTermVision: string;

  // Capital (step 3)
  useOfFunds: string;
  biggestChallenges: string;
  attendLagosEvent: string;

  // Commitment (step 4)
  whyConsidered: string;
  commitmentConfirmed: boolean;
  disclaimersAccepted: boolean;

  // Pipeline metadata
  dateApplied: string;
  currentStage: string;
  currentStatus: ApplicantStatus;
  lastUpdated: string | null;

  // Admin-only fields
  assignedReviewer: string | null;
  notes: string | null;
  nextActionRequired: string | null;

  // Response scheduling (cron-driven)
  adminResponse: string | null;
  emailResponseStatus: EmailResponseStatus;
  scheduledSendDate: string | null;

  // Video invite pipeline (Part A of run-review-batch)
  videoInviteWindow: VideoInviteWindow | null;
  videoInviteSentAt: string | null;
};

export type VideoSubmission = {
  id: VideoSubmissionId;
  applicantId: ApplicantId;
  videoLink: string;
  submittedAt: string;
  reviewStatus: VideoReviewStatus;
  feedback: string | null;
  approvedAt: string | null;
  rejectedAt: string | null;
  inviteEmailSentAt: string | null;
  /** Set when Part B of run-review-batch fires the verification invite. */
  verificationInviteSentAt: string | null;
  /** Set when Part C sends the training rejection email. */
  trainingEmailSentAt: string | null;
  /** Embed of the applicant for joined reads; admin-only reads. */
  applicantFirstName?: string;
  applicantLastName?: string;
  applicantEmail?: string;
};

export type Verification = {
  id: VerificationId;
  applicantId: ApplicantId;
  email: string;
  lpxId: string;          // generated by data layer (was a Postgres trigger)
  invitedAt: string | null;
  deadlineDate: string | null;
  formSubmitted: boolean;
  submittedAt: string | null;
  reviewStatus: VerificationReviewStatus;
  verificationFormPath: string | null;
  paymentReceiptPath: string | null;
};

export type EmailTemplate = {
  key: TemplateKey;
  subject: string;
  htmlBody: string;
  updatedAt: string;
};

export type VerificationBatch = {
  id: string;
  batchDate: string;       // YYYY-MM-DD
  whatsappLink: string;
};

export type SendLog = {
  id: string;              // RTDB push id
  applicantId: ApplicantId;
  templateKey: TemplateKey;
  sentAt: string;
};

export type EngineRunLog = {
  id: string;              // RTDB push id
  ranAt: string;
  videoInvitesSent: number;
  verificationInvitesSent: number;
  errorCount: number;
  errors: Array<{ stage: string; message: string; applicantId?: string }>;
};

/** Convenience type for admin list views. */
export type ApplicantSummary = Pick<
  Applicant,
  | "id"
  | "firstName"
  | "lastName"
  | "email"
  | "phone"
  | "currentStage"
  | "currentStatus"
  | "dateApplied"
  | "industry"
  | "businessName"
  | "businessStage"
  | "adminResponse"
  | "emailResponseStatus"
  | "scheduledSendDate"
  | "videoInviteWindow"
  | "assignedReviewer"
>;
